spring:
  profiles:
    active: jdbc
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.77.48:5432/fah
    username: jim
    password: pass

server:
  port: 9051

keycloak:
  auth-server-url: http://192.168.77.58:9500/auth
  realm: Fah
  resource: FahConfigServer
  public-client: true
#  security-constraints[0]:
#    authRoles[0]: Config-Admin
#    securityCollections[0]:
#      patterns[0]: /admin/*